### ISSUE TITLE
Sed command needs a workaround in mac OSS

### ISSUE THREAD

**Issue by tebayoso** [security-alliance/frameworks#58]
## What content are you looking to modify or update?
I want to update the `./serve.sh` script because the `sed` command works slightly different in Mac OS, making the setup process incompatible.

## Why do you think this update or modification is needed?
Some developers use MAC and will face this issue when trying to setup, collaborate and run this project.

## Can you justify your argument and provide additional resources
Although this script is a temporary fix to prevent the handlebars template from failing when serving the assets, it helps new developers onboard easily.

**Comment by mattaereal** [comment]
The need of the sed command has been deprecated, thankfully, so there's no need for this issue to remain open.
